name: lixtec
description: Um aplicativo Flutter para reciclagem de lixo eletrônico.
publish_to: 'none'

version: 2.0.0+7

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_modular: ^5.0.0
  get: ^4.6.6

  import_sorter: ^4.6.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.7
  asuka: ^2.2.1
  mobile_scanner: ^6.0.3
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.0
  latlong2: ^0.9.0
  http: ^1.3.0
  fluttertoast: ^8.2.10
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: '#A7C957'
  image: 'assets/icons/splash.png'
  android: true
  ios: true

flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  ios: true
  remove_alpha_ios: true
  android: 'launcher_icon'
  adaptive_icon_background: '#FFFF'
  adaptive_icon_foreground: 'assets/icons/app_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/tutorial/
    - assets/fonts/
