import { makeStyles } from '@material-ui/core'
import { colors } from '_config'

export const useStyles = makeStyles({
  container: {
    height: '97vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: colors.system.backgroundColors.primary,
  },
  header: {
    height: '100%',
    display: 'grid',
    rowGap: '1%',
    columnGap: '2%',
    justifyItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    gridTemplateColumns: '1fr 1fr',
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
  },
  title: {
    color: colors.system.textColors.primary,
    fontSize: 20,
    textTransform: 'capitalize',
  },
  icon: {
    color: colors.system.backgroundColors.primary,
  },
  buttonDeposits: {
    minWidth: '120px',
    minHeight: '120px',
    backgroundColor: colors.system.backgroundColors.secondary,
    display: 'grid',
    justifyItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  buttonRanking: {
    minWidth: '120px',
    minHeight: '120px',
    backgroundColor: colors.system.light.tertiary,
    display: 'grid',
    justifyItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  buttonAccount: {
    minWidth: '120px',
    minHeight: '120px',
    backgroundColor: colors.system.light.tertiary,
    display: 'grid',
    justifyItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  buttonAbout: {
    minWidth: '120px',
    minHeight: '120px',
    backgroundColor: colors.system.backgroundColors.secondary,
    display: 'grid',
    justifyItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  button: {
    minWidth: '120px',
    minHeight: '120px',
    backgroundColor: colors.system.backgroundColors.secondary,
    display: 'grid',
    justifyItems: 'center',
  },
  user: {
    display: 'flex',
    marginTop: '10px',
    justifyContent: 'space-around',
  },
  userName: { alignItems: 'center', display: 'flex', color: '#000000' },
  appBar: {
    width: '100%',
    height: '100px',
    backgroundColor: colors.system.backgroundColors.secondary,
  },
  welcomeTitle: {
    display: 'flex',
    color: colors.system.textColors.primary,
    justifyContent: 'center',
    lineHeight: '2.5',
    fontWeight: 700,
  },
  link: {
    fontWeight: 500,
    fontSize: '14px',
    color: colors.system.systemColors.secondary,
  },
  signOut: {
    display: 'flex',
    justifyContent: 'center',
  },
  signOutButton: {
    width: '100%',
    fontWeight: 700,
    fontSize: '14px',
    borderRadius: '30px',
    color: colors.system.neutralColors.primary,
    backgroundColor: `${colors.system.backgroundColors.secondary} !important`,
  },
})
